### ISSUE TITLE
Using Configuration File Causes Crash

### ISSUE THREAD

**Issue by gurudvlp** [gurudvlp/LinMoTube#3]
Currently loading configuration files fails.  This has the result of causing the app to not launch.

How to reproduce:

Create a configuration file in the default config path, like /home/mobian/.config/linmotube/linmotube.conf

Enter something into this file such as:

`resultquantity=5`

Attempt to launch the app.  It will crash with:
```

Config file not found: /etc/linmotube/linmotube.conf
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/LinMoTube-1.0-py3.9.egg/linmotube/__init__.py", line 263, in OnInit
    engine.loadConfig(engine.userConfig())
  File "/usr/local/lib/python3.9/dist-packages/LinMoTube-1.0-py3.9.egg/linmotube/engine.py", line 30, in loadConfig
    eline = strip(eline)
NameError: name 'strip' is not defined
OnInit returned false, exiting...
```

**Comment by gurudvlp** [comment]
This has been corrected.  It has also been verified that the configuration file is now supplying values appropriately.
